version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=app_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "/app/docker/web_command_dev.sh"
    volumes:
      - bundle_cache:/bundle
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=app_development
volumes:
  bundle_cache:
  postgres_data:
